### ISSUE TITLE
Verify env variables are informed

### ISSUE THREAD

**Issue by iwi** [iwi/linkatos#33]
When  env variables are wrong linkatos crashes. 

Quote from comment on a PR, with an example

> The following happened when testing the bot:
> 1. Add http://foo.com
> 2. Linkatos responds with “If you would like http://foo.com to be stored please react to it with a :+1:, if you would like it to be ignored use :-1:“
> 3. Add :+1: to the URL  
>
> Linkatos raises the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 443, in raise_detailed_error
    request_object.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./linkatos.py", line 43, in <module>
    firebase)
  File "/usr/local/linkatos/linkatos/activities.py", line 59, in event_consumer
    fb_credentials, firebase)
  File "/usr/local/linkatos/linkatos/reaction.py", line 25, in handle
    fb.connect_and_store_url(url, fb_credentials, firebase)
  File "/usr/local/linkatos/linkatos/firebase.py", line 41, in connect_and_store_url
    token = get_token(credentials, firebase)
  File "/usr/local/linkatos/linkatos/firebase.py", line 23, in get_token
    firebase.auth())
  File "/usr/local/linkatos/linkatos/firebase.py", line 17, in authenticate
    credentials['password'])
  File "/usr/local/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 85, in sign_in_with_email_and_password
    raise_detailed_error(request_object)
  File "/usr/local/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 446, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=] {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyInvalid",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
```
> Which is sort of expected given I don't have any Firebase credentials in place but it shows we should deal with this situation while starting the bot. In other words, we need to check if the env variables are informed and, if not, stop the bot logging a clear message explaining which piece of data wasn't provided at start time.

**Comment by ManoloCap** [comment]
Same!
